### ISSUE TITLE
Share gerber files

### ISSUE THREAD

**Issue by kagouraki** [OpenMarine/MacArthur-HAT#13]
Will you share the gerber files so some of us can make the boards our selfs? Today you launched the hat and after 5 minutes you took the website down... who knows if there are boards left and when they will be available again :(
Very good work though !

**Comment by sailoog** [comment]
Sorry for the server problem, too much demand, the server is up again and you can still find some units for sale.

We will still wait a bit to publish the Kicad files. First we want to recover the money invested and get some extra resources to stabilize the stock. We will then publish the files so that people can modify and adapt the HAT.

**Comment by sailoog** [comment]
Closed by https://github.com/OpenMarine/MacArthur-HAT/commit/a109cf125e574781115fbb9ef189cf731384045f
